### ISSUE TITLE
Issue commands from lighthouse?

### ISSUE THREAD

**Issue by ghost** [olzraiti/dotfiles#1]
First and foremost, thanks for the awesome configs.

Apart from the suggestions, there doesn't seem to be a way to launch terminal commands from lighthouse.. please advise.

**Comment by olzraiti** [comment]
Glad to contribute. :)

Well, first things first: are you piping lightouse queries to bash? If you call `lighthouse`, it will just echo the generated command. You need to pipe it to bash to execute it: `lighthouse | bash`.

My lighthouse configuration is pretty hacky. I have a custom built lighthouse binary file, which is needed by my lighthouse python files (the custom lighthouse build allows caching entered commands).

I added the modified source file that is needed to build lighthouse with my modification. You can't use the `lighthouse` in my bin, because the source file uses a hard coded path to my home. Clone lighthouse from the lighthouse repository, and replace `src/lighthouse.c' with this file: [lib/lighthouse.c](../blob/master/lib/lighthouse.c). Now replace all`/home/olli` with your home path (yes - it's really hard coded. I wrote that when I wasn't planning to release my dotfiles and it was the easiest solution since I didn't need to google up how to access environment variables in C). Then build lighthouse.

I personally use rofi nowadays, but feel free to hack around with the lighthouse configs.
