### ISSUE TITLE
How to properly setup the notification system

### ISSUE THREAD

**Issue by vsr625** [olzraiti/dotfiles#11]
First off, I would like to say that your config is the most advanced and functional. Thanks for posting it on github.

I'm trying to get the notification when switching desktops in bspwm, similar to what you have. I tried to understand what all things were going on in your config and tried to replicate that, the notification popps up, but the active desktop icons are not highlighted. And I have many questions regarding the notification setup.

1. What should be started in the startup, bar_notifyd or notifyd?
2. I am using zsh as my shell where should I specify the export stuff you have in your .profile 
3. I don't use xrandr, and so what should be the values of monitor-x and monitor-y variables present inside of bar_notifyd
4. There is a weird thing happening with notification when switching desktop. Look at the image. there is like a three icon notification on top of 6 icon notification.(this only happens sometimes) [image](http://imgur.com/pTVPpY1)
5. It would really be helpful if you can specify how to properly setup the notification backend, you have dunstrc in your config, but for running notifyd sid is run?

I have only tried with notify_focused_desktop. If that works as expected then I suppose all the other notification related things also would work fine. Thanks.

**Comment by olzraiti** [comment]
> the active desktop icons are not highlighted.

Are you using the grid layout with `scripts/bspwm/desktop_wall`? It doesn't work without it.

> 1. What should be started in the startup, bar_notifyd or notifyd?

`bar_notifyd`. To clarify, `bar_notifyd` is the stand alone notification system, which can be used with `notify` (also `notify-no-icon` for legacy/backward compability reasons). `bar_notifyd` can run separately on four corners of the screens - by default it uses the north eastern corner. `notifyd` starts a `bar_notifyd` at the south eastern corner, and directs free desktop notifications (the notifications that you would invoke with `notify-send`) to the `bar_notifyd` in the south eastern corner.

> 2. I am using zsh as my shell where should I specify the export stuff you have in your .profile

If you are using zsh as your login shell, i believe `.zprofile` is invoked upon login.

> 3. I don't use xrandr, and so what should be the values of monitor-x and monitor-y variables present inside of bar_notifyd

`$monitor_x/y` are the x/y offset. Most likely you can set them to 0. Read here: https://askubuntu.com/questions/614145/output-of-xrandr-shows-1024x76813660-what-does-it-mean-and-can-i-change-it

> 4. There is a weird thing happening with notification when switching desktop. Look at the image. there is like a three icon notification on top of 6 icon notification.(this only happens sometimes) image

`bar_notifyd` invokes multiple lemonbars for multiline notifications. Currently it just stacks them, so that there is a race condition where the first lemonbar is invoked after the second and it gets on the way of the latter lemonbar. I haven't gotten around to fix the heights of the lemonbars so that this wouldn't happen. 

> 5. It would really be helpful if you can specify how to properly setup the notification backend, you have dunstrc in your config, but for running notifyd sid is run?

Yeah, I used dunst previously. As I explained in the answer to the first question, sind is used to bind the free desktop notifications to `bar_notifyd`.

**Comment by vsr625** [comment]
Thanks for taking the time to reply, 
1. Now the workspace switching notification works as expected, I didn't run desktop_wall before, thanks.
2. I got clarification regarding to the bar_notifyd and notifyd. I think there is a small mistake in notifyd script.
echo $notification >> /dev/notify_fifo_southeast. but according to the bar_notifyd it should actually be /dev/shm/notify_fifo_southeast right, when I changed it to that, normal notifications also gets picked up by bar_notifyd. and there is also a typo in notify script "southheast" -> "southeast".
3. Yes, .zprofile worked perfectly
4. I am still facing the problem where sometimes oddly, the workspace switching notification will have a single row on top of what seems to be the normal two row notification. I had this even before desktop_wall script running, so it's mostly in the notify_focused_desktop script, I didn't get where that problem might be causing. I have changed the icons to be displayed in single row, so nothing to worry about this.

Next, I'm trying to replicate the dropdown terminals similar to yours, as they could be really helpful, before I dig in and try to understand how everything works, can you give me a brief on how to set it up. it would save me a lot of time.

Thanks.
Edit: I tried to add the dropdown terminal, since I don't use xrandr what should be the values of width height in the get_end_pos script. that is causing error inside of quakify script.

**Comment by vsr625** [comment]
I figured it out. Thanks.
