### ISSUE TITLE
Multiple Monitor Support

### ISSUE THREAD

**Issue by ghost** [olzraiti/dotfiles#4]
I really like the idea of a grid workspace layout, and I was wondering how hard/time-consuming would it be to expand the desktop_wall script to work for multiple monitors. I was thinking that each monitor would have their own grid of workspaces and the grid notification would be drawn on the focused monitor. I am thinking that I'm going to have to figure this out with my limited knowledge, but I wanted to see if you would give me some ideas on how you would go about doing this. Any help would be appreciated.

**Comment by olzraiti** [comment]
It's definitely possible - you need to expand bin/bar_notifyd so that you could start a different notification listener for each monitor. That's the hard part, since the code is pretty messy. Then you would need to modify the bin/notify_focused_desktop. That part should be pretty easy.

bin/bar_notifyd is described in more detail in #3
