### ISSUE TITLE
Using Pass to autofill passwords and usernames?

### ISSUE THREAD

**Issue by LiVeenMusic** [olzraiti/dotfiles#5]
Hey man! I've gotten so far as to get to the part where it asks me to pick what password I want to enter, from a list, but as soon as I pick a password, Rofi closes, and nothing happens to the password form. What could be wrong?  
  
This happens when I just do paste_pass in Termite:  
  
`[chris@ARCH ~]$ paste_pass  
etitään window anme  
You specified the wrong number of args.  
Usage: type [--window windowid] [--delay milliseconds] <things to type>  
--window <windowid>    - specify a window to send keys to  
--delay <milliseconds> - delay between keystrokes  
--clearmodifiers       - reset active modifiers (alt, etc) while typing  
--args N  - how many arguments to expect in the exec command. This is  
            useful for ending an exec and continuing with more xdotool
            commands  
--terminator TERM - similar to --args, specifies a terminator that
                    marks the end of 'exec' arguments. This is useful
                    for continuing with more xdotool commands.  
--file <filepath> - specify a file, the contents of which will be
                    be typed as if passed as an argument. The filepath
                    may also be '-' to read from stdin.  
-h, --help             - show this help output  
/home/chris/.config/i3/scripts/wp/paste_pass: line 7: notify-no-icon: command not found`

**Comment by LiVeenMusic** [comment]
Little update: I got it to somewhat do things? I realized I had just left your own email in the pass files, and now changed it to mine. Everything seems to work ok-ish. When I try to use the paste_pass or paste_user function in a website where I have the password, what it does is it opens rofi back up again, and then types it into rofi, instead of the user form. How can I avoid this? I believe it is the last thing necessary for this to work, but I've been unable to find out how to avoid rofi opening back up again.

**Comment by olzraiti** [comment]
Hey there,

First of all: I recommend checking out [rofi-pass](https://github.com/carnager/rofi-pass) and [autopass](https://github.com/jreinert/autopass), as those are maintained and meant for other people to use, instead of my hacky scripts which I didn't write with the intention that it would be easy for anyone else than me to use. :-) When I wrote the rofi pass prompt, I made the mistake that I didn't first check if someone had implemented something similar already. I still use it though - I'm not sure if it has some benefits over those two projects. My implementation checks window titles to find the right password entry automatically - this works in many cases very well.

As I mentioned, the scripts are hacky. The bug you described (password being written to a immediately spawned rofi prompt) happens on my setup sometimes also. I think it's because some of the temp files aren't cleared correctly in some cases. It happens so rarely to me that I hadn't gotten around to fix the script.

In your error log it reads at least that your $PATH doesn't contain the `notify-no-icon` variable. Try replacing it with `notify-send` - the `notify-no-icon` is used for my custom notification system.

**Comment by LiVeenMusic** [comment]
Ah, I see. Yeah, now the notification definitely works. Did you have some way you used to make sure the rofi script of yours worked better?

Nevertheless, I'll check out the links you sent me! Thank you! :)

**Comment by olzraiti** [comment]
I use the same version of the rofi pass script that is in this repo. If the bug happens, I open a console and run `rm /tmp/pass_*` to clean the state.

**Comment by LiVeenMusic** [comment]
I see. Thank you very much for your help! I'll go ahead and close this now! :+1:
